# Generated by Django 3.2.13 on 2022-06-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='Скрыть новость'),
        ),
    ]
