# Generated by Django 3.2.13 on 2022-06-29 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_alter_news_advisor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date_of_pub'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
