# Generated by Django 3.2.13 on 2022-05-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ac_dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_s', models.DateField(null=True, verbose_name='Начало уч. года')),
                ('year_e', models.DateField(null=True, verbose_name='Конец уч. года')),
                ('module1_s', models.DateField(null=True, verbose_name='Начало модуля 1')),
                ('module1_e', models.DateField(null=True, verbose_name='Конец модуля 1')),
                ('module2_s', models.DateField(null=True, verbose_name='Начало модуля 2')),
                ('module2_e', models.DateField(null=True, verbose_name='Конец модуля 2')),
                ('module3_s', models.DateField(null=True, verbose_name='Начало модуля 3')),
                ('module3_e', models.DateField(null=True, verbose_name='Конец модуля 3')),
                ('module4_s', models.DateField(null=True, verbose_name='Начало модуля 4')),
                ('module4_e', models.DateField(null=True, verbose_name='Конец модуля 4')),
            ],
            options={
                'verbose_name': 'Академический календарь',
                'verbose_name_plural': 'Академические даты',
                'ordering': ['year_s'],
            },
        ),
    ]
