# Generated by Django 3.2.13 on 2022-05-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_calendars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ac_dates',
            name='fx1_e',
            field=models.DateField(null=True, verbose_name='Конец FX(з)'),
        ),
        migrations.AddField(
            model_name='ac_dates',
            name='fx1_s',
            field=models.DateField(null=True, verbose_name='Начало FX(з)'),
        ),
        migrations.AddField(
            model_name='ac_dates',
            name='fx2_e',
            field=models.DateField(null=True, verbose_name='Конец FX(л)'),
        ),
        migrations.AddField(
            model_name='ac_dates',
            name='fx2_s',
            field=models.DateField(null=True, verbose_name='Начало FX(л)'),
        ),
        migrations.AddField(
            model_name='ac_dates',
            name='i1_e',
            field=models.DateField(null=True, verbose_name='Конец I(з)'),
        ),
        migrations.AddField(
            model_name='ac_dates',
            name='i1_s',
            field=models.DateField(null=True, verbose_name='Начало I(з)'),
        ),
        migrations.AddField(
            model_name='ac_dates',
            name='i2_e',
            field=models.DateField(null=True, verbose_name='Конец I(л)'),
        ),
        migrations.AddField(
            model_name='ac_dates',
            name='i2_s',
            field=models.DateField(null=True, verbose_name='Начало I(л)'),
        ),
        migrations.AlterField(
            model_name='ac_dates',
            name='module1_e',
            field=models.DateField(null=True, verbose_name='Конец М1'),
        ),
        migrations.AlterField(
            model_name='ac_dates',
            name='module1_s',
            field=models.DateField(null=True, verbose_name='Начало М1'),
        ),
        migrations.AlterField(
            model_name='ac_dates',
            name='module2_e',
            field=models.DateField(null=True, verbose_name='Конец М2'),
        ),
        migrations.AlterField(
            model_name='ac_dates',
            name='module2_s',
            field=models.DateField(null=True, verbose_name='Начало М2'),
        ),
        migrations.AlterField(
            model_name='ac_dates',
            name='module3_e',
            field=models.DateField(null=True, verbose_name='Конец М3'),
        ),
        migrations.AlterField(
            model_name='ac_dates',
            name='module3_s',
            field=models.DateField(null=True, verbose_name='Начало М3'),
        ),
        migrations.AlterField(
            model_name='ac_dates',
            name='module4_e',
            field=models.DateField(null=True, verbose_name='Конец М4'),
        ),
        migrations.AlterField(
            model_name='ac_dates',
            name='module4_s',
            field=models.DateField(null=True, verbose_name='Начало М4'),
        ),
    ]
