# Generated by Django 3.2.13 on 2022-05-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_calendars', '0002_auto_20220519_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='ac_dates',
            name='name',
            field=models.CharField(max_length=9, null=True, verbose_name='Период'),
        ),
        migrations.AlterField(
            model_name='ac_dates',
            name='fx1_e',
            field=models.DateField(null=True, verbose_name='Конец FX(зим.)'),
        ),
        migrations.AlterField(
            model_name='ac_dates',
            name='fx1_s',
            field=models.DateField(null=True, verbose_name='Начало FX(зим.)'),
        ),
        migrations.AlterField(
            model_name='ac_dates',
            name='fx2_e',
            field=models.DateField(null=True, verbose_name='Конец FX(лет.)'),
        ),
        migrations.AlterField(
            model_name='ac_dates',
            name='fx2_s',
            field=models.DateField(null=True, verbose_name='Начало FX(лет.)'),
        ),
        migrations.AlterField(
            model_name='ac_dates',
            name='i1_e',
            field=models.DateField(null=True, verbose_name='Конец I(зим.)'),
        ),
        migrations.AlterField(
            model_name='ac_dates',
            name='i1_s',
            field=models.DateField(null=True, verbose_name='Начало I(зим.)'),
        ),
        migrations.AlterField(
            model_name='ac_dates',
            name='i2_e',
            field=models.DateField(null=True, verbose_name='Конец I(лет.)'),
        ),
        migrations.AlterField(
            model_name='ac_dates',
            name='i2_s',
            field=models.DateField(null=True, verbose_name='Начало I(лет.)'),
        ),
    ]
