# Generated by Django 3.2.13 on 2022-05-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_calendars', '0003_auto_20220519_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ac_dates',
            options={'ordering': ['year_s'], 'verbose_name': 'Академическую дату', 'verbose_name_plural': 'Академические даты'},
        ),
    ]
