# Generated by Django 3.2.13 on 2022-05-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_calendars', '0004_alter_ac_dates_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ac_periods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Название периода')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Период регистрации',
                'verbose_name_plural': 'Периоды регистрации',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Ac_dates',
        ),
    ]
