# Generated by Django 3.2.13 on 2022-05-19 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_calendars', '0005_auto_20220519_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ac_years',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Учебный год')),
                ('date_start', models.DateField(verbose_name='Начало учебного года')),
                ('date_end', models.DateField(verbose_name='Конец учебного года')),
            ],
            options={
                'verbose_name': 'Учебный год',
                'verbose_name_plural': 'Учебные годы',
                'ordering': ['-name'],
            },
        ),
        migrations.AddField(
            model_name='ac_periods',
            name='years',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_calendars.ac_years', verbose_name='Учебный год'),
        ),
    ]
