# Generated by Django 3.2.13 on 2022-05-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_calendars', '0006_auto_20220519_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ac_periods',
            options={'ordering': ['id'], 'verbose_name': 'Период учебного года', 'verbose_name_plural': 'Периоды учебного года'},
        ),
    ]
