# Generated by Django 3.2.13 on 2022-05-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_calendars', '0007_alter_ac_periods_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ac_periods',
            options={'ordering': ['date_start', 'date_end'], 'verbose_name': 'Период учебного года', 'verbose_name_plural': 'Периоды учебного года'},
        ),
    ]
