# Generated by Django 3.2.13 on 2022-05-19 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_calendars', '0008_alter_ac_periods_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ac_periods',
        ),
    ]
