# Generated by Django 3.2.13 on 2022-05-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_calendars', '0009_delete_ac_periods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ac_years',
            old_name='date_end',
            new_name='year_e',
        ),
        migrations.RenameField(
            model_name='ac_years',
            old_name='date_start',
            new_name='year_s',
        ),
    ]
