# Generated by Django 3.2.13 on 2022-05-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_calendars', '0010_auto_20220519_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ac_years',
            options={'ordering': ['year_s', 'year_e'], 'verbose_name': 'Учебный год', 'verbose_name_plural': 'Учебные годы'},
        ),
        migrations.AddField(
            model_name='ac_years',
            name='fx1_e',
            field=models.DateField(null=True, verbose_name='Конец FX (зим.)'),
        ),
        migrations.AddField(
            model_name='ac_years',
            name='fx1_s',
            field=models.DateField(null=True, verbose_name='Начало FX (зим.)'),
        ),
        migrations.AddField(
            model_name='ac_years',
            name='fx2_e',
            field=models.DateField(null=True, verbose_name='Конец FX (лет.)'),
        ),
        migrations.AddField(
            model_name='ac_years',
            name='fx2_s',
            field=models.DateField(null=True, verbose_name='Начало FX (лет.)'),
        ),
        migrations.AddField(
            model_name='ac_years',
            name='i1_e',
            field=models.DateField(null=True, verbose_name='Конец I (зим.)'),
        ),
        migrations.AddField(
            model_name='ac_years',
            name='i1_s',
            field=models.DateField(null=True, verbose_name='Начало I (зим.)'),
        ),
        migrations.AddField(
            model_name='ac_years',
            name='i2_e',
            field=models.DateField(null=True, verbose_name='Конец I (лет.)'),
        ),
        migrations.AddField(
            model_name='ac_years',
            name='i2_s',
            field=models.DateField(null=True, verbose_name='Начало I (лет.)'),
        ),
        migrations.AddField(
            model_name='ac_years',
            name='m1_e',
            field=models.DateField(null=True, verbose_name='Конец M1'),
        ),
        migrations.AddField(
            model_name='ac_years',
            name='m1_s',
            field=models.DateField(null=True, verbose_name='Начало M1'),
        ),
        migrations.AddField(
            model_name='ac_years',
            name='m2_e',
            field=models.DateField(null=True, verbose_name='Конец M2'),
        ),
        migrations.AddField(
            model_name='ac_years',
            name='m2_s',
            field=models.DateField(null=True, verbose_name='Начало M2'),
        ),
        migrations.AddField(
            model_name='ac_years',
            name='m3_e',
            field=models.DateField(null=True, verbose_name='Конец M3'),
        ),
        migrations.AddField(
            model_name='ac_years',
            name='m3_s',
            field=models.DateField(null=True, verbose_name='Начало M3'),
        ),
        migrations.AddField(
            model_name='ac_years',
            name='m4_e',
            field=models.DateField(null=True, verbose_name='Конец M4'),
        ),
        migrations.AddField(
            model_name='ac_years',
            name='m4_s',
            field=models.DateField(null=True, verbose_name='Начало M4'),
        ),
        migrations.AlterField(
            model_name='ac_years',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Учебный год'),
        ),
        migrations.AlterField(
            model_name='ac_years',
            name='year_e',
            field=models.DateField(null=True, verbose_name='Конец года'),
        ),
        migrations.AlterField(
            model_name='ac_years',
            name='year_s',
            field=models.DateField(null=True, verbose_name='Начало года'),
        ),
    ]
