# Generated by Django 3.2.13 on 2022-05-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0008_auto_20220515_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advisor',
            options={'verbose_name': 'Советник', 'verbose_name_plural': 'Советники'},
        ),
    ]
