# Generated by Django 3.2.13 on 2022-05-15 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0009_alter_advisor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advisor',
            options={'ordering': ['id'], 'verbose_name': 'Советник', 'verbose_name_plural': 'Советники'},
        ),
        migrations.AlterField(
            model_name='advisor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ID Пользователя'),
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Наименование группы')),
                ('cours', models.IntegerField(null=True, verbose_name='Курс')),
                ('advisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_users.advisor', verbose_name='ID Советника')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['cours', '-name'],
            },
        ),
    ]
