# Generated by Django 3.2.13 on 2022-05-16 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0010_auto_20220515_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_e',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True, verbose_name='Форма обучения')),
            ],
            options={
                'verbose_name': 'Форма обучения',
                'verbose_name_plural': 'Формы обучения',
                'ordering': ['-name'],
            },
        ),
        migrations.AddField(
            model_name='groups',
            name='credit_price',
            field=models.IntegerField(null=True, verbose_name='Стоимость кредита'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_users.advisor', verbose_name='Советник'),
        ),
        migrations.AddField(
            model_name='groups',
            name='form_of_e',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_users.form_e', verbose_name='Форма обучения'),
        ),
    ]
