# Generated by Django 3.2.13 on 2022-05-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0014_auto_20220517_0114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advisor',
            options={'ordering': ['id'], 'verbose_name': 'Советника', 'verbose_name_plural': '2. Советники'},
        ),
        migrations.AlterModelOptions(
            name='form_e',
            options={'ordering': ['-name'], 'verbose_name': 'Форму обучения', 'verbose_name_plural': 'Формы обучения'},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'ordering': ['-cours', '-name'], 'verbose_name': 'Группу', 'verbose_name_plural': '3. Группы'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-cipher', '-id'], 'verbose_name': 'Студента', 'verbose_name_plural': '4. Студенты'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-is_superuser', '-is_advisor', 'full_name'], 'verbose_name': 'Пользователя', 'verbose_name_plural': '1. Пользователи'},
        ),
    ]
