# Generated by Django 3.2.13 on 2022-05-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0015_auto_20220519_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-is_superuser', '-is_advisor', 'is_teacher', 'full_name'], 'verbose_name': 'Пользователя', 'verbose_name_plural': '1. Пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_advisor',
            field=models.BooleanField(default=False, verbose_name='Cоветник'),
        ),
    ]
