# Generated by Django 3.2.13 on 2022-05-23 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0016_auto_20220521_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'ordering': ['-cours', '-name'], 'verbose_name': 'Группу', 'verbose_name_plural': '4. Группы'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-cipher', '-id'], 'verbose_name': 'Студента', 'verbose_name_plural': '5. Студенты'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-is_superuser', '-is_advisor', '-is_teacher', 'full_name'], 'verbose_name': 'Пользователя', 'verbose_name_plural': '1. Пользователи'},
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50, null=True, verbose_name='Должность')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ID Пользователя')),
            ],
            options={
                'verbose_name': 'Преподавателя',
                'verbose_name_plural': '3. Преподаватели',
                'ordering': ['id'],
            },
        ),
    ]
