# Generated by Django 3.2.13 on 2022-05-23 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0017_auto_20220523_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisor',
            name='position',
        ),
    ]
