# Generated by Django 3.2.13 on 2022-06-07 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_disciplines', '0019_auto_20220607_1123'),
        ('app_users', '0018_remove_advisor_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_disciplines.department', verbose_name='Отделение'),
        ),
    ]
