# Generated by Django 3.2.13 on 2022-05-19 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form_controls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название формы контроля')),
            ],
            options={
                'verbose_name': 'Форму контроля',
                'verbose_name_plural': 'Формы контроля',
            },
        ),
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('short_name', models.CharField(max_length=75, verbose_name='Короткое название')),
                ('credits', models.IntegerField(null=True, verbose_name='Количество кредитов')),
                ('hours', models.IntegerField(null=True, verbose_name='Количество часов')),
                ('form_control', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_disciplines.form_controls', verbose_name='Форма контроля')),
            ],
            options={
                'verbose_name': 'Дисциплину',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
    ]
