# Generated by Django 3.2.13 on 2022-05-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_disciplines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_controls',
            name='short_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Название формы контроля'),
        ),
        migrations.AlterField(
            model_name='form_controls',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Название формы контроля'),
        ),
    ]
