# Generated by Django 3.2.13 on 2022-05-19 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0015_auto_20220519_1503'),
        ('app_disciplines', '0002_auto_20220519_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplines',
            options={'ordering': ['-name'], 'verbose_name': 'Дисциплину', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.AlterModelOptions(
            name='form_controls',
            options={'ordering': ['-name'], 'verbose_name': 'Форму контроля', 'verbose_name_plural': 'Формы контроля'},
        ),
        migrations.AlterField(
            model_name='form_controls',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='form_controls',
            name='short_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Короткое название'),
        ),
        migrations.CreateModel(
            name='Discipline_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_reg', models.DateField(verbose_name='Дата регистрации')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_disciplines.disciplines', verbose_name='Название дисциплины')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_users.student', verbose_name='ФИО Студента')),
            ],
            options={
                'verbose_name': 'Регистрацию на предмет',
                'verbose_name_plural': 'Регистрации на предметы',
            },
        ),
    ]
