# Generated by Django 3.2.13 on 2022-05-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_disciplines', '0003_auto_20220519_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline_reg',
            name='date_of_reg',
            field=models.DateField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
    ]
