# Generated by Django 3.2.13 on 2022-05-19 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0015_auto_20220519_1503'),
        ('app_disciplines', '0004_alter_discipline_reg_date_of_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='period_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Название периода')),
            ],
            options={
                'verbose_name': 'Период регистрации',
                'verbose_name_plural': 'Периоды регистрации',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='discipline_reg',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_users.student', verbose_name='Шифр студента'),
        ),
        migrations.AddField(
            model_name='disciplines',
            name='period_reg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_disciplines.period_reg', verbose_name='Период регистрации'),
        ),
    ]
