# Generated by Django 3.2.13 on 2022-05-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_disciplines', '0005_auto_20220519_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplines',
            name='period_reg',
        ),
        migrations.DeleteModel(
            name='period_reg',
        ),
    ]
