# Generated by Django 3.2.13 on 2022-05-19 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_calendars', '0008_alter_ac_periods_options'),
        ('app_disciplines', '0006_auto_20220519_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplines',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_calendars.ac_periods', verbose_name='Период регистрации'),
        ),
    ]
