# Generated by Django 3.2.13 on 2022-05-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_disciplines', '0008_auto_20220519_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credits_count',
            options={'ordering': ['dis_reg'], 'verbose_name': 'Колличество кредитов', 'verbose_name_plural': 'Колличество кредитов'},
        ),
    ]
