# Generated by Django 3.2.13 on 2022-05-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_disciplines', '0009_alter_credits_count_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplines',
            options={'ordering': ['name'], 'verbose_name': 'Дисциплину', 'verbose_name_plural': 'Дисциплины'},
        ),
        migrations.RemoveField(
            model_name='disciplines',
            name='period',
        ),
    ]
