# Generated by Django 3.2.13 on 2022-05-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_disciplines', '0010_auto_20220519_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplines',
            name='fh',
            field=models.BooleanField(null=True, verbose_name='Первое полугодие'),
        ),
        migrations.AddField(
            model_name='disciplines',
            name='sh',
            field=models.BooleanField(null=True, verbose_name='Второе полугодие'),
        ),
        migrations.AddField(
            model_name='disciplines',
            name='xtr',
            field=models.BooleanField(null=True, verbose_name='Дополнительно'),
        ),
    ]
