# Generated by Django 3.2.13 on 2022-05-23 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0018_remove_advisor_position'),
        ('app_disciplines', '0011_auto_20220519_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplines',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app_users.teacher', verbose_name='Преподаватель'),
        ),
    ]
