# Generated by Django 3.2.13 on 2022-05-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_disciplines', '0012_disciplines_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline_reg',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Регистрация подтверждена'),
        ),
    ]
