# Generated by Django 3.2.13 on 2022-06-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_disciplines', '0015_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='faculty_cipher',
            field=models.IntegerField(null=True, verbose_name='Шифр факультета'),
        ),
    ]
