# Generated by Django 3.2.13 on 2022-06-07 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_disciplines', '0016_faculty_faculty_cipher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='faculty_cipher',
            new_name='cipher',
        ),
    ]
