# Generated by Django 3.2.13 on 2022-06-07 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_disciplines', '0017_rename_faculty_cipher_faculty_cipher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('short_name', models.CharField(max_length=50, verbose_name='Короткое название')),
                ('сipher', models.IntegerField(null=True, verbose_name='Шифр отделения')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_disciplines.faculty', verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
            },
        ),
    ]
