# Generated by Django 3.2.13 on 2022-06-09 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_disciplines', '0019_auto_20220607_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Кафедру', 'verbose_name_plural': '2. Кафедры'},
        ),
    ]
