# Generated by Django 3.2.13 on 2022-06-10 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0019_groups_department'),
        ('app_disciplines', '0022_alter_discipline_reg_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline_reg',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='app_disciplines.disciplines', verbose_name='Название дисциплины'),
        ),
        migrations.AlterField(
            model_name='discipline_reg',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student', to='app_users.student', verbose_name='Шифр студента'),
        ),
    ]
