# Generated by Django 3.2.13 on 2022-06-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_disciplines', '0023_auto_20220610_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline_reg',
            name='academ_a',
            field=models.BooleanField(default=False, verbose_name='Отказ советника'),
        ),
        migrations.AddField(
            model_name='discipline_reg',
            name='academ_c',
            field=models.BooleanField(default=False, verbose_name='Подтверждение советника'),
        ),
    ]
