# Generated by Django 3.2.13 on 2022-06-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_disciplines', '0025_discipline_reg_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline_reg',
            name='hide',
            field=models.BooleanField(default=False, verbose_name='Скрыть результат'),
        ),
    ]
