# Generated by Django 3.2.13 on 2022-06-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_disciplines', '0026_discipline_reg_hide'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline_reg',
            name='course',
            field=models.IntegerField(null=True, verbose_name='Курс'),
        ),
    ]
