# Generated by Django 3.2.13 on 2022-06-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_disciplines', '0027_discipline_reg_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline_reg',
            name='course',
        ),
        migrations.AddField(
            model_name='disciplines',
            name='course',
            field=models.IntegerField(null=True, verbose_name='Курс'),
        ),
    ]
