# Generated by Django 3.2.13 on 2022-06-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_disciplines', '0028_auto_20220617_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplines',
            options={'ordering': ['course', 'department'], 'verbose_name': 'Дисциплину', 'verbose_name_plural': '4. Дисциплины'},
        ),
        migrations.AddField(
            model_name='discipline_reg',
            name='bad',
            field=models.BooleanField(default=False, verbose_name='Не закрыт'),
        ),
        migrations.AddField(
            model_name='discipline_reg',
            name='good',
            field=models.BooleanField(default=False, verbose_name='Закрыт'),
        ),
    ]
