# Generated by Django 3.2.13 on 2022-06-29 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_disciplines', '0030_auto_20220629_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline_reg',
            name='bad_mark',
        ),
        migrations.RemoveField(
            model_name='discipline_reg',
            name='good_mark',
        ),
    ]
