# Generated by Django 3.2.13 on 2022-06-29 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_disciplines', '0031_auto_20220629_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline_reg',
            name='bad',
            field=models.BooleanField(default=False, verbose_name='Не закрыт'),
        ),
        migrations.AddField(
            model_name='discipline_reg',
            name='good',
            field=models.BooleanField(default=False, verbose_name='Закрыт'),
        ),
    ]
